version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4007:4007"
    volumes:
      - .:/app 
    env_file:
      - .env
    command: npm run dev
